### ISSUE TITLE
sslocal in version 3.4.1 is not compatible with the new protocal

### ISSUE THREAD

**Issue by jack33232** [breakwa11/shadowsocks#10]
When I update the shadowsocks into the new version and turn on the toggle in tcprelay.py to True.
The sslocal will not work and say cannot parse header in log. Can you help? Thanks~ I need sslocal running on RPi for all my other devices.

**Comment by breakwa11** [comment]
I think I should prove the new protocol is a good solution or nonsense first. sslocal not support the new protocol now
