### ISSUE TITLE
请问日志里没有IP和访问网站的记录吗？

### ISSUE THREAD

**Issue by PioneerCloud** [breakwa11/shadowsocks#101]
RT.请问日志里没有IP和访问网站的记录吗？

或者如何能加一下

现在的日志里只有报错和密码的添加记录

**Comment by liyangio** [comment]
是的，我的也是没有用户访问的IP。。不太好控制他们去访问一些违法IP。。。辛苦作者能够加上访问日志。

**Comment by breakwa11** [comment]
user-config.json或config.json里有一个连接详细log的项，改为1
