### ISSUE TITLE
sspanelv3于sspanelv3ssr有什么区别？

### ISSUE THREAD

**Issue by spencerxiong** [breakwa11/shadowsocks#105]
API_INTERFACE = 'sspanelv2' #mudbjson, sspanelv2, sspanelv3, sspanelv3ssr, muapiv2(not support)

sspanelv3于sspanelv3ssr有什么区别？

**Comment by breakwa11** [comment]
sspanelv3ssr加了自定义混淆和协议及其参数，需要数据库表有支持
