### ISSUE TITLE
服务器多ip，多出口怎么弄？

### ISSUE THREAD

**Issue by RainierBig** [breakwa11/shadowsocks#106]
ss libev 版本实现过
ssr libev 只有客户端功能

manyuser版本能不能实现多ip，多个出口，就是我指定哪个ip访问，返回来的还是我指定的ip？

**Comment by breakwa11** [comment]
早就实现了，能不能不要问已经实现了的东西

**Comment by RainierBig** [comment]
实在不好意思。。。刚好我的第二个测试ip有问题，没有跑起来
第三个ip ok了 
sorry for that...
