### ISSUE TITLE
"Balance" feature with python client

### ISSUE THREAD

**Issue by hdid** [breakwa11/shadowsocks#108]
Hi
Does python client support the "balance" feature ( "port_password" )? Because i could not use that option and got password error. This is my config:

{
    "server": "xx.xx.xx.xx",
    "port_password":{
        "6062":{"password":"abcddddd", "protocol":"verify_deflate", "obfs":"tls1.2_ticket_auth"},
        "6568":{"password":"defggggg", "protocol":"auth_sha1_v2", "obfs":"http_simple"},
        "7561":{"password":"dcbaaaaa", "protocol":"verify_sha1", "obfs":"tls1.0_session_auth"},
        "4563":{"password":"gfeddddd", "protocol":"verify_simple", "obfs":"random_head"},
        "3142":{"password":"abcdefgh", "protocol":"auth_sha1", "obfs":"tls_simple"}
    },
    "local_address": "10.9.8.1",
    "local_port": 1080,
    "timeout": 300,
    "udp_timeout": 140,
    "method": "chacha20",
    "dns_ipv6": false,
    "fast_open": true
}

@breakwa11

**Comment by hdid** [comment]
@breakwa11 any update?

**Comment by breakwa11** [comment]
I will try to support

**Comment by breakwa11** [comment]
dup #31
