### ISSUE TITLE
懵逼人士求问

### ISSUE THREAD

**Issue by TheHooper** [breakwa11/shadowsocks#110]
![image](https://cloud.githubusercontent.com/assets/11960949/17592040/4761eb7e-6013-11e6-893e-2e16e3f63012.png)

请问就这样并不能连是什么情况，之前是用的ss-manyuser 一切正常的，今天把他删了，装的你的ssr-manyuser，不知道什么情况，日志文件也没，用脚本运行，日志文件为0kb

客户端也是用的ssr

**Comment by breakwa11** [comment]
你怎么配置的？
