### ISSUE TITLE
ShadowsocksR服务端是不是跳过了Hosts文件？修改hosts文件无效果

### ISSUE THREAD

**Issue by ToyoDAdoubi** [breakwa11/shadowsocks#114]
我想要屏蔽一些网站，想到的是修改hosts文件屏蔽，但是Shadowsocks服务端依然不受影响。
VPS上面ping被屏蔽的域名也是正常127.0.0.1。
是不是ShadowsocksR服务端直接跳过了本地hosts文件？
还是有缓存啥的。
如果是的话，怎么做呢？

**Comment by ToyoDAdoubi** [comment]
蛋疼，重启VPS后正常了。

**Comment by breakwa11** [comment]
重启SS服务端就行了，host文件它是启动时读取的
