### ISSUE TITLE
manyuser版本udp问题

### ISSUE THREAD

**Issue by 1294822** [breakwa11/shadowsocks#121]
使用最新版的manyuser版本，客户端使用ssr3741，开启tcp over udp，但无法爬墙。ss服务端也没有任何日志，config文件里面的日志等级写了4。服务器udp端口开放了，抓包也看到服务器收到了udp的数据了。应该是udprelay没响应吧，应该怎么继续分析或者还是啥地方配置有问题？谢谢

**Comment by breakwa11** [comment]
do not support tcp over udp
