### ISSUE TITLE
tcprelay.py:117 create encryptor fail at port

### ISSUE THREAD

**Issue by didila** [breakwa11/shadowsocks#122]
之前一直可以使用，只是简单的将config.json 的auth_sha1_v2改为auth_sha1_v4
这下问题出来了
Server (JSON  Ver. Updated)
2016-09-24 15:46:35 INFO     server.py:98 server start with protocol[auth_sha1_v4] method [aes-256-cfb] obfs [tls1.2_ticket_auth] obfs_param [0]
2016-09-24 15:47:20 ERROR    tcprelay.py:117 create encryptor fail at port xx

Client (3.9.0)
[2016-09-24 15:38:56] [Error]Proxy server [(104.xx.xx.xx)] ClientPostDecrypt data error
无论我怎么改Server和Client设定，始终出现这个问题
再改回auth_sha1_v2错误持续出现
20个server大约有6个出现同样的错误，其他是正常的
我有centos6.6和ubunut14.04
而问题好像都集中在centos6.6
我更新了libsodium和shadowsocks问题还是一样

**************
另外我发现每个主机都有的不影响应用状况
config.json公用设定为"method":"aes-256-cfb"
我单独设定某一个port为 "method":"chacha20-ietf"
可是log显示却是 method [aes-256-cfb]
是不是log输出套用错误了？

**Comment by breakwa11** [comment]
第一，服务端更新了没有，更新后有重启吗
二，我不知道你服务端的模式
log输出是不会错的，你是配置方式错误

**Comment by didila** [comment]
都更新了，也重启了
服务端是json单人版
{
    "server":"0.0.0.0",
    "port_password":{
    	"123":{"protocol":"auth_sha1_v4", "method":"chacha20-ietf", "password":"xxxxxx"},
      "211":"xxxxxx",
     	"124":"xxxxxx",
    	"125":{"protocol":"origin", "method":"chacha20-ietf", "password":"xxxxxx"},
    	"126":"xxxxxx",
    	"127":{"protocol":"origin", "password":"xxxxxx"},
      "128":"xxxxxx",
      "129":"xxxxxx"
    },
    "timeout":300,
    "method":"aes-256-cfb",
    "protocol": "auth_sha1_v2",
    "protocol_param": "",
    "obfs": "tls1.2_ticket_auth",
    "obfs_param": "",
    "redirect": “”, 
    "dns_ipv6": false,
    "fast_open": true,
    "workers": 3
}
唯独auth_sha1_v4出问题
而log的问题很久以前我就有发现，只是因为无关紧要就没提出

**Comment by breakwa11** [comment]
你clone的什么分支什么地址

**Comment by didila** [comment]
git clone -b manyuser https://github.com/breakwa11/shadowsocks.git

**Comment by breakwa11** [comment]
你为什么还只复制子目录，为什么不直接在那目录里运行

**Comment by didila** [comment]
只是强迫症作祟而已，因为看wiki说明貌似子目录是独立的，所以我就独自复制运行

**Comment by breakwa11** [comment]
配置文件的redirect后面引号是错的

**Comment by didila** [comment]
redirect拿掉就好了。不过，即使redirect是错的会影响到，应该全部端口都会出错才对啊，
可是却只有"123":{"protocol":"auth_sha1_v4", "method":"chacha20-ietf", "password":"xxxxxx"},这一项不能用，
我现在解决的方式是改回原来的设定
"123":{"method":"chacha20-ietf", "password":"xxxxxx"},
也就是说我无法设置为auth_sha1_v4
而且很确定同样的设定复制贴上，只有centos6.6才会这样，ubuntu14.04是正常的

**Comment by breakwa11** [comment]
我觉得你要查查，因为那个提示表明代码是旧的，才会create fail
