### ISSUE TITLE
关于实现服务器搭建SS多用户相同端口的方法

### ISSUE THREAD

**Issue by 41340218** [breakwa11/shadowsocks#123]
当前版本多用户，还处于多个不同用户使用不同端口可以登录，而不同用户使用同一个端口却无法登陆，不知是否有哪位大神能够修改下用户登录的验证方式。
例如：
数据库中有以下三个用户：
A为用户，端口123，连接密码123123；
B为用户，端口200，连接密码200200；
C为用户，端口200，连接密码300300；（其他条件设置相同）
现在情况是：A和B用户均可以连接，网络通畅，而C用户不能正常使用。而如果C用户使用密码200200则可以正常使用，这就是多人公用一个账号。
修改思路：通过修改SS文件的用户连接验证方式，当A或B用户连接时不变，C用户连接时，相应代码搜索数据库中端口为200的B用户，获取B用户的密码让C用户连接（相当于使用B用户密码和端口连接），C相当于B的子用户，而流量统计是ABC用户各自计算，A和B为超级用户，可以再增加D用户为A或B的子用户，这样控制用户使用SS会更加合理且方便，超级用户也可以和子用户数据库表分开，希望哪位大神能做一下，或者告诉我服务器中哪个文件是用户登录连接时验证密码和端口的函数或文件，或者有什么其他的方法也可以
我的目的：能够使相同端口且不同SS连接密码的用户（例如B和C）都能正常连接网络，不同用户SS连接密码不同且相同端口的用户流量能单独计录并更新在数据库

**Comment by breakwa11** [comment]
@41340218 目前还不支持

**Comment by 41340218** [comment]
@breakwa11 能告诉我ss客户端与搭建有SS的服务器的哪个文件进行对接验证连接的吗？

**Comment by breakwa11** [comment]
@41340218 协议层面上就不支持，强行这么做只会产生很多莫名其妙的问题
