### ISSUE TITLE
http_post的boundary怎么写才对？

### ISSUE THREAD

**Issue by hweidz** [breakwa11/shadowsocks#125]
server:2.9.5
client:3.9.5

在参数里写成如下格式，客户端和服务端都配置了相同参数，但是始终连不上

 "obfs_param": "baidu.com#Content-Type: multipart/form-data; boundary=----WebKitFormBoundarypGFNyDqSZzMCeBJ5",

server端报错：
ERROR    tcprelay.py:878 can not parse header when handling connection from 192.168.100.100:55540

**Comment by breakwa11** [comment]
@hweidz 服务端不支持这种格式，以及你真的确认了你服务端版本了没有？麻烦把你的Log连同版本号发完整

**Comment by hweidz** [comment]
loaded collections.OrderedDict
IPv6 support
INFO: loading config from /data/shadowsocksr/ssr.json
2016-10-13 16:34:32 INFO     util.py:85 loading libsodium from libsodium.so.13
2016-10-13 16:34:32 INFO     shell.py:80 ShadowsocksR 2.9.5 2016-10-13

**Comment by breakwa11** [comment]
@hweidz 服务端不要填写obfs param

**Comment by hweidz** [comment]
"obfs_param": "",这样写 ？

还是直接去掉这个参数？

**Comment by breakwa11** [comment]
@hweidz 不要填写就是保持默认值或留空
