### ISSUE TITLE
混淆方式与耗电量的疑问

### ISSUE THREAD

**Issue by nexusman2016** [breakwa11/shadowsocks#126]
目前在Android 6.0.1的手机上使用ShadowsocksR，比较注重耗电量的问题
当前组合是Wiki中推荐的auth_aes128_md5 + http_post + rc4 加密
请问这种混淆和加密方式与原版的不混淆+chacha20 相比，耗电量有没有显著的增加呢？
选择哪种混淆方式最省电呢？
谢谢

**Comment by chobitsos** [comment]
这个根本就不是ISSU，你去G+ R组提
