### ISSUE TITLE
后端出现2个报错 can not parse header和unsupported addrtype 153, maybe wrong password

### ISSUE THREAD

**Issue by Arnaud-Github** [breakwa11/shadowsocks#13]
![xshot-0042](https://cloud.githubusercontent.com/assets/11697277/9865020/f056fddc-5b82-11e5-8bd4-f55b54f771fe.png)

就在上Github这会儿又来了，我也不太清楚这是什么情况，我也很好奇为什么只有我显示了端口号而且报出这两个错误，这没有影响到我正常使用，但我还是想解决这个问题，有好的办法吗？

**Comment by PlaneV** [comment]
选错加密方式了吧
2015年9月15日 上午8:25，"Arnaud" <notifications@github.com>写道：

**Comment by Arnaud-Github** [comment]
@PlaneV 如果加密方式选择错误了不是不能连接吗？我可以正常使用，但是会报出这两个Warning

**Comment by breakwa11** [comment]
是不是有其它人在用你服务器，但他没配置正确导致的？或者可能是你所在地区的主动探测扫描等等。。。。而且你用的版本不是我的

**Comment by Arnaud-Github** [comment]
@breakwa11 我已经解决问题了，版本是mengskysama的，然后我忘记杀掉旧版的进程，换成你的了。
