### ISSUE TITLE
请问多用户版是否支持单独对用户设置加密、混淆和协议吗？

### ISSUE THREAD

**Issue by evilkong** [breakwa11/shadowsocks#131]
请问多用户版是否支持单独对用户设置加密、混淆和协议吗？
另外还有一个，能否做到修改配置（比如换了一种加密）后直接下发通知到客户端（或者用户连接时只要密码端口正确，自动更新其加密、协议和混淆）自动修改？针对python_manyuser + c#客户端

**Comment by glzjin** [comment]
支持，不支持。

**Comment by evilkong** [comment]
谢谢解答、我是python_manyuser，然后连接的mysql的。拔特，db_transfer.py 这里面没有去user上面拉取加密、混淆和协议，以及对应的参数。目前要自己改文件。期望作者直接支持。

**Comment by breakwa11** [comment]
@evilkong 你需要读wiki里面的多用户说明，你需要设置为sspanelv3ssr模式

**Comment by evilkong** [comment]
@breakwa11 谢谢，又回去拜读了下wiki，都点了一遍，但接口处的说明都是一带而过。没有太详细的解说。所以没太留意。然后发现设置为sspanelv3ssr模式后，一切问题都自动解决了。之前以为没支持，直接自己去改了db_transfer.py 。。。 还有流量日志，很久很久以前没有支持的时候，写了个user的mysql触发脚本。然后发现这些破娃酱大大都已经搞定了。膜拜+感激ing
