### ISSUE TITLE
manyuser版在windows上的openssl兼容性问题

### ISSUE THREAD

**Issue by sanjusss** [breakwa11/shadowsocks#134]
我在windows2003 32位的系统上启动ssr服务端。
如果我安装的openssl是Win32OpenSSL-1_1_0c.exe的话，会提示找不到OpenSSL库。
如果安装Win32OpenSSL-1_0_2j.exe的话，正常启动。
看了下两个版本OpenSSL的bin目录，发现库文件数量、名字均不相同。

**Comment by breakwa11** [comment]
所以只是没安装对，而不是兼容性问题
