### ISSUE TITLE
must be string or buffer, not dict

### ISSUE THREAD

**Issue by chenTest2013** [breakwa11/shadowsocks#138]
version:2.6.10
服务器环境：ubun14.04 
执行：/shadowsocks/shadowsocks/server.py -c ssr.json
ssr.json如下：
{
    "server":"0.0.0.0",
    "server_ipv6":"::",
    "local_address":"127.0.0.1",
    "local_port":1080,
    "port_password":{
        "1430":{"protocol":"auth_sha1_v4", "password":"NzE5NGJjMW", "obfs":"tls1.2_ticket_auth", "obfs_param":""},
        "1431":{"protocol":"auth_aes128", "password":"NzE5NGJjMW","obfs":"tls1.2_ticket_auth"}
    },
    "timeout":300,
    "method":"aes-256-cfb",
    "protocol": "auth_sha1_compatible",
    "protocol_param": "",
    "obfs": "http_simple_compatible",
    "obfs_param": "",
    "redirect": "",
    "dns_ipv6": false,
    "user":"nobody",
    "fast_open": true,
    "workers": 2
}

配置文件按照这样，服务总是启动报错，不知是何原因
日志报错信息：must be string or buffer, not dict
只有这一个错误，没有其他的了

**Comment by breakwa11** [comment]
能写完整吗（我在我这个回复里也故意省略了一点东西你看你猜到我指什么东西要写完整吗

**Comment by chenTest2013** [comment]
@breakwa11 只有这一个错误，没有其他的了

**Comment by breakwa11** [comment]
啥时候补充写完整了再找我，只写错误信息让我猜迷我不会

**Comment by chenTest2013** [comment]
可以了
