### ISSUE TITLE
一切配置完成之后使用Python server.py报了一个错误

### ISSUE THREAD

**Issue by YouZiQian** [breakwa11/shadowsocks#139]
![image](https://cloud.githubusercontent.com/assets/8923844/21071950/ab6635d4-beec-11e6-9c2f-9a627458af2a.png)
如何解决

**Comment by breakwa11** [comment]
你到底设置的interface是什么

**Comment by YouZiQian** [comment]
没有设置interface啊...

**Comment by breakwa11** [comment]
我感觉你设置是错的，你还没和我说你到底怎么设置的，到底要多用户还是单用户，多用户又是哪个模式

**Comment by YouZiQian** [comment]
是多用户数据库模式呀

**Comment by breakwa11** [comment]
你的数据库表似乎有问题

**Comment by YouZiQian** [comment]
是的...谢谢破娃
不过又出来另一个问题,服务端运行不报错 防火墙端口全开 但是客户端就是连接不上.
下面是服务端运行截图
![image](https://cloud.githubusercontent.com/assets/8923844/21072262/3782ecd8-bef7-11e6-84e4-da4ca0c46adc.png)

**Comment by breakwa11** [comment]
一个用户都没有，自然就是这样，一个端口都没有开

**Comment by YouZiQian** [comment]
我的数据库中是有用户的.端口密码总流量什么的也都是设置过了
![image](https://cloud.githubusercontent.com/assets/8923844/21072370/e764fd8c-befa-11e6-8d26-ca4f975fa8bc.png)

**Comment by breakwa11** [comment]
你的总流量T不是0吗？根本就是不能使用的用户

**Comment by YouZiQian** [comment]
transfer_enable不是总流量吗...

**Comment by breakwa11** [comment]
你每个字段的类型发来看看，还有数据库的字符串编码

**Comment by YouZiQian** [comment]
![image](https://cloud.githubusercontent.com/assets/8923844/21072468/ee7748ba-befe-11e6-9a87-cef27afd5057.png)

**Comment by breakwa11** [comment]
你这个表明显不是sspanel v2的表

**Comment by YouZiQian** [comment]
这是我自建的表啊...

**Comment by YouZiQian** [comment]
前端页面和管理后台都是自己做的

**Comment by breakwa11** [comment]
那这可能需要你自己查查了

**Comment by breakwa11** [comment]
还有一点，你查查API_INTERFACE的设置，看你需要支持到什么程度，可支持自定义加密方式甚至自定义协议和混淆
