### ISSUE TITLE
请问要怎么限制同一个用户只能在一处登录?

### ISSUE THREAD

**Issue by YouZiQian** [breakwa11/shadowsocks#140]
或者说要如何获得某个用户是否在线的状态

**Comment by breakwa11** [comment]
使用auth协议限制客户端数量为2，查看在线状态需要配合面板v3

**Comment by YouZiQian** [comment]
auth_simple协议吗

**Comment by breakwa11** [comment]
任何auth前缀的都可以，建议auth_aes128_md5

**Comment by YouZiQian** [comment]
为所有用户配置协议只需要在config.json中协定protocol就可以了是吗

**Comment by breakwa11** [comment]
不，协议参数还要填写，参数值是最大同时在线客户端数量，最少值为2

**Comment by YouZiQian** [comment]
2016-12-12 15:36:00 WARNING  common.py:228 unsupported addrtype 69, maybe wrong password or encryption method
 在修改了协议之后报了这个错

**Comment by breakwa11** [comment]
你客户端没改

**Comment by YouZiQian** [comment]
客户端只有修改加密方式的呀

**Comment by YouZiQian** [comment]
这个问题好像是讲obfs从默认的tls1.2_ticket_auth_compatible改为tls1.2_ticket_auth之后出现的.

**Comment by breakwa11** [comment]
客户端必须匹配协议和混淆

**Comment by YouZiQian** [comment]
主要是客户端没找着配置协议和混淆的地方...
