### ISSUE TITLE
http_simple解决了移动对不符合规范的HTTP请求随机reset的问题

### ISSUE THREAD

**Issue by wu360463231** [breakwa11/shadowsocks#16]
海螺有开发安卓版或其他版本加入HTTP头混淆的打算吗？：）
还有个建议，HTTP头的IP/域名可以随机生成域名。不一定要固定连接的IP/域名

**Comment by breakwa11** [comment]
域名问题已经想过了，以后会加入配置项的

**Comment by akw28888** [comment]
然而福建移動http_simple混淆已經無效..

**Comment by xiaohuanshu** [comment]
请问现在这个问题解决了吗？
