### ISSUE TITLE
最近SS服务老是出错，翻不了，求解决

### ISSUE THREAD

**Issue by liuchao0130** [breakwa11/shadowsocks#19]
- -算了 。。重装一下试试

**Comment by breakwa11** [comment]
开了又关了是什么情况？

**Comment by liuchao0130** [comment]
额，因为我也不好怎么描述，  最近SSR服务端老是中断，   有时候等一会就好了， 大部分时候都需要重启服务器才会恢复。 
 分布在不同的机房的SS服务器都出现这个情况，  包括linode  HWL .  有什么办法吗？ 或者去哪里查看这个问题的原因呢
