### ISSUE TITLE
setup.py 错误

### ISSUE THREAD

**Issue by hand515** [breakwa11/shadowsocks#23]
packages=['shadowsocks', 'shadowsocks.crypto', 'shadowsocks.obfsplugin'],

缺少后面那项，python setup.py install 后会提示找不到obfsplugin

**Comment by falseen** [comment]
setup.py很久没更新了，不用安装也能用的

**Comment by falseen** [comment]
使用说明在这 https://github.com/breakwa11/shadowsocks-rss
