### ISSUE TITLE
单用户版protocol的设定语法？

### ISSUE THREAD

**Issue by sonicprogrammer** [breakwa11/shadowsocks#28]
2015年11月2日新版以后，protocol和obfs分开来。请问一下原先为每个端口配置不同obfs的写法：
"port_password":{
        "8388":["password1","http_simple"],
        "8389":["password2","random_head"]
    },
在新的版本下如何带上protocol选项字段？

非常感谢

**Comment by breakwa11** [comment]
配置方法已写入[wiki](https://github.com/breakwa11/shadowsocks-rss/wiki/Server-Setup)

**Comment by sonicprogrammer** [comment]
看到了，刚刚也看代码找出来了。谢谢。
close issue
