### ISSUE TITLE
如何通过auth_simple限制单一端口连接的客户端数？

### ISSUE THREAD

**Issue by a2232189** [breakwa11/shadowsocks#29]
wiki里没有细说。

**Comment by breakwa11** [comment]
需要改源代码，在verify_simple.py里搜索“max active client count”

**Comment by falseen** [comment]
其实我觉得没必要严格的限制客户端数量，限制ip数量可能会好一些。

**Comment by PlaneV** [comment]
请问怎么限定IP数量？
2015年11月13日 下午12:09，"Falseen" <notifications@github.com>写道：

**Comment by falseen** [comment]
实现起来也不难，我昨天已经帮朋友写了一个了，勉强可以用。只是这种实现方式需要修改tcprelay.py文件，不利于ss的更新。
如果你需要的话我可以发给你，在gitter上私密我（如果你有的话）。

**Comment by PlaneV** [comment]
多谢大神！

**Comment by breakwa11** [comment]
现在直接在配置文件里修改protocol_param就可以了
