### ISSUE TITLE
出现错误，但上网正常。

### ISSUE THREAD

**Issue by zhwalker** [breakwa11/shadowsocks#33]
<code>2015-12-04 13:20:52 ERROR    Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 160, in thread_db
    DbTransfer.get_instance().push_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 48, in push_db_all_user
    dt_transfer[id] = [int(curr_transfer[id][0] * Config.MYSQL_TRANSFER_MUL),
AttributeError: 'module' object has no attribute 'MYSQL_TRANSFER_MUL'</code>
是不是下面这个commit引起的?
b5da4bc86a4fee5dbb61b7ca748df47d510cbf85

**Comment by breakwa11** [comment]
你需要更新Config.py

**Comment by zhwalker** [comment]
oh, sorry 没注意到

**Comment by zhwalker** [comment]
不过MYSQL_TRANSFER_MUL具体是干什么用的？

**Comment by breakwa11** [comment]
如果需要某节点的流量统计翻倍，就设置这个值为2.0
