### ISSUE TITLE
频繁出现查询SS数据库错误问题

### ISSUE THREAD

**Issue by kaneawk** [breakwa11/shadowsocks#35]
2015-12-07 10:53:10 ERROR    Traceback (most recent call last):
  File "/usr/local/etc/shadowsocks/db_transfer.py", line 160, in thread_db
    DbTransfer.get_instance().push_db_all_user()
  File "/usr/local/etc/shadowsocks/db_transfer.py", line 48, in push_db_all_user
    dt_transfer[id] = [int(curr_transfer[id][0] * Config.MYSQL_TRANSFER_MUL),
AttributeError: 'module' object has no attribute 'MYSQL_TRANSFER_MUL'

经常出现查询SS数据库丢失的问题。新增SS账户以后，需要重启SS服务端才能使新账户正常使用，真是无语了。不是丢包问题，同一运营商的服务器，相对延迟绝对不超过0.6ms。

**Comment by kaneawk** [comment]
这真是受不了了，每次更新user表的用户，都要手动重启服务端，才能让新用户使用，服务器比较多，并且重启客户端会影响到其他用户！！！这太麻烦了！之前应该是好好的，最近才出现的这种状况。开发者来看看这是哪里的问题？

**Comment by ZeroClover** [comment]
https://github.com/breakwa11/shadowsocks/issues/33

这个Issues和你情况一样，新版本Config.py新增一个MYSQL_TRANSFER_MUL，需要删掉原来的Config.py再git pull

**Comment by kaneawk** [comment]
哦？？

**Comment by breakwa11** [comment]
完整更新即可
