### ISSUE TITLE
shadowsocks-rm manyuser版能增加个功能，从memcache读取user表信息吗？

### ISSUE THREAD

**Issue by javacty** [breakwa11/shadowsocks#37]
只有你们2个大大还在维护了，向你们求助：
        我在国外的3个vps上部署了shadowsocks-rm manyuser版，管理网站ss-panel放在国内的vps，数据库也是放在这个国内的vps上，3个国外的vps共用网站的数据库。

问题：
网站时而会卡一下，大部分时间还比较快，mysql做了下慢查询记录：
Time: 151209 11:08:25
User@Host: ss_lrb[ss_lrb] @ [133.130.0.0]
Thread_id: 3104 Schema: shadowsocks QC_hit: No
Query_time: 61.113150 Lock_time: 0.000190 Rows_sent: 1512 Rows_examined: 1512
SET timestamp=1449630505;
SELECT port, u, d, transfer_enable, passwd, switch, enable FROM user;

Time: 151209 11:08:44
User@Host: ss_xmg[ss_xmg] @ [163.44.0.0]
Thread_id: 3145 Schema: shadowsocks QC_hit: No
Query_time: 60.193568 Lock_time: 0.000201 Rows_sent: 904 Rows_examined: 904
SET timestamp=1449630524;
SELECT port, u, d, transfer_enable, passwd, switch, enable FROM user;
Time: 151209 11:11:06
User@Host: ss_xmg[ss_xmg] @ [163.44.0.0]
Thread_id: 3259 Schema: shadowsocks QC_hit: No
Query_time: 24.040012 Lock_time: 0.000225 Rows_sent: 1512 Rows_examined: 1512
SET timestamp=1449630666;
SELECT port, u, d, transfer_enable, passwd, switch, enable FROM user;

Time: 151209 11:12:13
User@Host: ss_xmg[ss_xmg] @ [163.44.0.0]
Thread_id: 3307 Schema: shadowsocks QC_hit: No
Query_time: 8.165709 Lock_time: 0.000247 Rows_sent: 1512 Rows_examined: 1512
SET timestamp=1449630733;
SELECT port, u, d, transfer_enable, passwd, switch, enable FROM user;

不知是不是因为持续的update，清空了select缓存并且阻塞了select，我想:
shadowsocks-rm manyuser版能不能加个功能，从memcache读取user表信息吗？，update流量还是在mysql上，解决锁争用问题？

谢谢！

**Comment by breakwa11** [comment]
不建议数据库服务器与vps服务器分隔国内外，可能会很慢甚至被block
