### ISSUE TITLE
可以指定用户名运行manyuser服务端吗？

### ISSUE THREAD

**Issue by 70599** [breakwa11/shadowsocks#38]

**Comment by breakwa11** [comment]
数据库版？不能

**Comment by HooinKyoma** [comment]
使用supervisor运行服务端可以指定运行身份，配置文件中加入user=xxx即可。

**Comment by RainierBig** [comment]
@breakwa11 个人版呢？sudo -u xxx来运行服务端

**Comment by breakwa11** [comment]
> 使用supervisor运行服务端可以指定运行身份，配置文件中加入user=xxx即可。

这个就是解决办法
