### ISSUE TITLE
manyuser 版也可以多 worker 运行吗？

### ISSUE THREAD

**Issue by humiaozuzu** [breakwa11/shadowsocks#42]
看了下 manyuser 的代码并没有支持

**Comment by mikelei8291** [comment]
可以啊，`config.json` 里最后一行 `"workers": ` 参数

**Comment by humiaozuzu** [comment]
@mikelei8291 非 manyuser 版启动时用的 `shadowsocks/server.py`，才读取了 workers 参数

**Comment by superfls** [comment]
非manyuser启动的是shadowsocks/shadowsocks/server.py

**Comment by breakwa11** [comment]
不支持
