### ISSUE TITLE
服务器端运行几天无法使用了老报错WARNING IPV4 error: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by op2009** [breakwa11/shadowsocks#43]
服务器端运行几天无法使用了老报错
WARNING IPV4 error: [Errno 98] Address already in use
测试发现，运行几天后，居然出现两个 python server.py 导致服务端 端口被占用一直报错，什么问题，20台服务器 同时报错

**Comment by breakwa11** [comment]
https://github.com/breakwa11/shadowsocks-rss/issues/190
