### ISSUE TITLE
使用 verify_sha1 连接协议后 shadowsocks-android UDP转发出错

### ISSUE THREAD

**Issue by mikelei8291** [breakwa11/shadowsocks#44]
shadowsocks-rss客户端同时打开一次性认证和UDP转发后无法查询DNS，而libev版服务端则可以同时打开

**Comment by breakwa11** [comment]
python服务端的verify_sha1改成了完全兼容libev的UDP，c#版本还没有更新，不过应该是兼容的。另外我没有听明白你的问题，到底是哪个客户端？以及哪个服务端

**Comment by mikelei8291** [comment]
服务端: shadowsocks-rss
客户端: shadowsocks-android
服务端 protocol: verify_sha1
客户端配置: 一次性认证+UDP转发
结果: 浏览器查询DNS失败
但是只要关了UDP转发就可以正常运行，服务端换libev可以在客户端打开两个设置的时候正常使用

**Comment by mikelei8291** [comment]
等等，服务端更新后似乎问题被修复了
