### ISSUE TITLE
关于无法安装的问题

### ISSUE THREAD

**Issue by testcaoy7** [breakwa11/shadowsocks#45]
运行python setup.py install之后再系统中运行ssserver是不会成功的，提示出错：
ImportError: No module named obfsplugin。
应该是setup.py的问题，脚本没有更新过，没有把新增的obfplugin安装到系统导致的。

手动运行python server.py的所有功能正常。

另：混淆协议后，在电信线路下Youtube可以看480P了，EC2的服务器

**Comment by breakwa11** [comment]
不要用setup
