### ISSUE TITLE
同样的配置在不同服务器上UDP效果不一致

### ISSUE THREAD

**Issue by ZeroClover** [breakwa11/shadowsocks#47]
均为Linode CentOS 7服务器，IP未被墙

使用路由器插件（梅林）通过ss-tunnel发送加密UDP连接到服务器，A服务器可以看到有UDP data to xxxxx，B服务器没有，导致如果连接B服务器使用ss-tunnel就无法打开网站

同样，B服务器上也接收不到UDP数据，梅林选择游戏模式，B服务器上没有UDP data的信息

**Comment by breakwa11** [comment]
应该不属于软件问题，我自己测试时也发现有的服务器发i动任何UDP包，但TCP是正常的
