### ISSUE TITLE
manyuser 引用的是哪个版本的shadowsocks

### ISSUE THREAD

**Issue by qiuzi** [breakwa11/shadowsocks#5]
是不是在2.6.12基础上增加数据库版本？

**Comment by breakwa11** [comment]
现在的是2015/08/03的版本（2.7），马上会更新到python的2.8.2版

**Comment by qiuzi** [comment]
2.8貌似就多了api接口而已

**Comment by breakwa11** [comment]
会考虑更换为使用API的方式管理

**Comment by qiuzi** [comment]
API方式会去掉数据库支持？ 每个服务器都独立管理？

2015-08-11 21:20 GMT+08:00 breakwa11 <notifications@github.com>:
