### ISSUE TITLE
Cannot set "protocol" through command line

### ISSUE THREAD

**Issue by testcaoy7** [breakwa11/shadowsocks#51]
"protocol" can only be set by config file.

command line options are:

  -c CONFIG              path to config file
  -s SERVER_ADDR         server address, default: 0.0.0.0
  -p SERVER_PORT         server port, default: 8388
  -k PASSWORD            password
  -m METHOD              encryption method, default: aes-256-cfb
  -o OBFS                obfsplugin, default: http_simple
  -t TIMEOUT             timeout in seconds, default: 300
  --fast-open            use TCP_FASTOPEN, requires Linux 3.7+
  --workers WORKERS      number of workers, available on Unix/Linux
  --forbidden-ip IPLIST  comma seperated IP list forbidden to connect
  --manager-address ADDR optional server manager UDP address, see wiki

Where no flags correspond with "protocol"

**Comment by breakwa11** [comment]
-P protocol
-G protocol_param
-g obfs_param
