### ISSUE TITLE
一旦使用chacha20-ietf就会上不了

### ISSUE THREAD

**Issue by mountainguan** [breakwa11/shadowsocks#53]
![](http://i4.tietuku.com/c404d4983ba2c73d.jpg)
问题大概是这样的，完全不知道什么原因~换成chacha20就好了，服务端和客户端都是最新

我用的是py版的

**Comment by hanzexu990323** [comment]
檢查libsodium的版本

**Comment by mountainguan** [comment]
@hanzexu990323 1.07

**Comment by wongsyrone** [comment]
末尾的逗号没有影响么，代码应该是没什么问题，调用的都是外部实现
ref: https://github.com/breakwa11/shadowsocks/blob/manyuser/shadowsocks/crypto/sodium.py#L111

**Comment by mountainguan** [comment]
@wongsyrone 那我再更新一下libsodium试试
