### ISSUE TITLE
manyuser ！windows 下 python2.7.11  如果连接太多就会死掉  too many file descriptors in select()

### ISSUE THREAD

**Issue by ruan11223344** [breakwa11/shadowsocks#55]
貌似是 windows下select的支持数量不是很多，导致了死掉。
求方法~ IOCP 完全瞎了眼，求助。
PS:windows server 2008r2 x64
manyuser 版本是 2.6.13
python      版本是 python2.7.11 x64

**Comment by ruan11223344** [comment]
在线等，求大神出现。

**Comment by ruan11223344** [comment]
等了一天，没人出现。我明天再来 0 — 0

**Comment by breakwa11** [comment]
这个无解。。。你只能限制一下listen的数量比如降低到256

**Comment by ruan11223344** [comment]
谢谢@breakwa11  那我自己再试试看~
