### ISSUE TITLE
ftp不行

### ISSUE THREAD

**Issue by ghostry** [breakwa11/shadowsocks#58]
这里提供的sock5是不是和ssh提供的不太一样。

我的fliezilla如果用ss的sock5就提示超时，如果用同一服务器的ssh的就正常使用。

**Comment by breakwa11** [comment]
ss提供的socks5不是完整实现，现在所有的分支都不能支持ftp代理

**Comment by breakwa11** [comment]
因为ftp需要支持bind操作，ss从来没有实现，或者你可以试试使用被动FTP模式

**Comment by ghostry** [comment]
@breakwa11 原来如此，被动也不行。感谢解答。

**Comment by breakwa11** [comment]
总之，用sftp替代，问题就肯定解决了
