### ISSUE TITLE
能否加入DDNS功能

### ISSUE THREAD

**Issue by wan-qy** [breakwa11/shadowsocks#60]
突发奇想想用几个在国外的同学的电脑搭梯子，不过都是动态IP那么就想到了DDNS；想在shadowsocks服务端加入DDNS功能~~然而蒟蒻一只并不会写~~所以求助breakwa11啦(๑•ั็ω•็ั๑)

资料倒是有一些：[DDNS](http://i4.tietuku.com/2e17713dd2b425cf.png)

**Comment by tutugreen** [comment]
(⊙o⊙)…好像和SS没啥关系，可以找其他代码。。（DDNS更新脚本之类的）
