### ISSUE TITLE
如何设置只允许plan为x的用户连接

### ISSUE THREAD

**Issue by Dwwwwww** [breakwa11/shadowsocks#61]
RT

**Comment by breakwa11** [comment]
修改相应节点的switchrule.py

**Comment by Dwwwwww** [comment]
谢谢。

**Comment by geniusxiaoxiao** [comment]
switchrule.py能不能设置成planA和planB？
貌似我测试了下只能限制一种。目的是我做了个脚本让到期用户表为其他的plan，以减轻ss服务器的压力(少加载用户)

**Comment by breakwa11** [comment]
@geniusxiaoxiao  那个是python，你想怎么限制代码就怎么写
