### ISSUE TITLE
 ERROR 'odict_iterator' object has no attribute 'next'

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [breakwa11/shadowsocks#64]
维护服务器的时候的时候看到许多这样的这样的log
python[18842]: 时间 INFO TCP connecting 网站 from 网站IP
python[18842]: 时间 ERROR 'odict_iterator' object has no attribute 'next'
python[18842]: loaded collections.OrderedDict
python[18842]: IPv6 support
然后就退出
systemd[1]: shadowsocksR.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: shadowsocksR.service: Unit entered failed state.
systemd[1]: shadowsocksR.service: Failed with result 'exit-code'.
systemd[1]: shadowsocksR.service: Service hold-off time over, scheduling restart.
之后就重启

而且使用的时候经常是一个网站要刷新两次才能进去
刚才更新到了最新版本b9aefc1还是如此

系统是最新版archlinux
服务器拥有IPv6地址块

**Comment by Lyoko-Jeremie** [comment]
刚才一个一个版本退回测试
发现从14 Dec 2015的 improve LRUCache 
“aff97d4ce8cba4dc8835037981512e22686fe0b3”
这个版本开始就有这个问题了

前一个版本improve tls_simple  10 Dec 2015
aa92a5940570143d8bcc694f778a014a1db484c8
没有问题

**Comment by breakwa11** [comment]
测试一下现在的版本看看

**Comment by Lyoko-Jeremie** [comment]
已经修复
最新版貌似没有这个问题了

**Comment by Lyoko-Jeremie** [comment]
另外刚又发现一个问题
https://github.com/breakwa11/shadowsocks/issues/65
