### ISSUE TITLE
“为每个端口配置不同的混淆协议”无法使用，类型错误？

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [breakwa11/shadowsocks#65]
在对特定端口使用配置特定混淆协议时失败

配置文件：

<pre>
{
 "server":"0.0.0.0",
 "server_ipv6": "[::]",
 "local_address":"127.0.0.1",
 "local_port":1080,
 "port_password":{
 "端口":"密码",
 "端口":"密码",
 "端口":"密码",
 "端口":"密码",
 "端口":
    {
     "protocol":"auth_sha1",
     "protocol_param": "",
     "password":"密码",
     "obfs":"random_head",
     "obfs_param":""
    }
 },
 "protocol":"auth_sha1_compatible",
 "protocol_param": "",
 "obfs":"random_head_compatible",
 "obfs_param": "",
 "timeout":300,
 "dns_ipv6": false,
 "redirect": "bing.jp",
 "method":"aes-256-cfb",
 "fast_open": false
}
</pre>

错误信息：

<pre>
INFO     server start with protocol[b'auth_sha1'] password [b'密码'] method [aes-256-cfb] obfs [b'random_head'] obfs_param [b''] 
INFO     starting server at [b'[::]']:端口 
ERROR    method b'auth_sha1' not supported 
INFO     starting server at 0.0.0.0:端口 
ERROR    method b'auth_sha1' not supported 
INFO     server start with protocol[auth_sha1_compatible] password [b'密码'] method [aes-256-cfb] obfs [random_head_compatible] obfs_param [] 
INFO     starting server at [b'[::]']:端口 
ERROR    [Errno -2] Name or service not known 
INFO     starting server at 0.0.0.0:端口 
INFO     server start with protocol[auth_sha1_compatible] password [b'密码'] method [aes-256-cfb] obfs [random_head_compatible] obfs_param [] 
INFO     starting server at [b'[::]']:端口 
ERROR    [Errno -2] Name or service not known 
INFO     starting server at 0.0.0.0:端口 
</pre>
错误信息里第一个“server start with protocol”的就是单独配置了协议的
后面两个都是没有单独配置的
然后现在后两个可以用，单独配置的那个就不能用
看起来是把所有字段都看作字符串了.....

**Comment by breakwa11** [comment]
你的python具体是哪个版本？我手上没有复现问题的版本

**Comment by breakwa11** [comment]
貌似已fix

**Comment by 70599** [comment]
现在有办法在manyuser分支为不同端口配置不同的加密方式吗？
