### ISSUE TITLE
最近多用户版无法获取新用户···

### ISSUE THREAD

**Issue by serm12** [breakwa11/shadowsocks#66]
最近多用户版无法获取新用户···
不知道什么情况

**Comment by j0hnnie** [comment]
同理，都出现问题了

**Comment by iloveuMissliao** [comment]
我也是.....必须手动重启服务端才可以，希望尽快解决

**Comment by breakwa11** [comment]
你们肯定是配置文件更新的时候出错，但没有管（就是那个Confg.py合并出错，这不是我的问题），重新git clone再配置最简单
