### ISSUE TITLE
老大，希望日志系统能做优化

### ISSUE THREAD

**Issue by evilkong** [breakwa11/shadowsocks#71]
目前tail.sh看到的日志信息里面是没有带端口的，我看了下源码，python不是太懂，不会改。。。
另外，如果这个日志可以选择是否直接入数据库就更好了。

btw，MANAGE_PASS / MANAGE_BIND_IP / MANAGE_PORT 
这三个是怎么使用的？

**Comment by kaneawk** [comment]
当初我提交过一个 push，但被拒绝了，后来才想到了原因……
大概 @breakwa11 最讨厌网络审查类的东西。So, SSR ori 日志是不可能做优化的。

不过你可以用我改的：https://github.com/kaneawk/shadowsocks/commits/mu
