### ISSUE TITLE
连接日志

### ISSUE THREAD

**Issue by piero66** [breakwa11/shadowsocks#77]
有没有可以看到客户端某个端口的连接日志。好像只有一个ssserver.log。但看不到客户端端口的连接信息。
就是有没有如下的日志，能直接看到哪个用户连接到哪个网站的
2015-06-10 00:05:07 INFO     connecting xx.ntdtv.com:80 from 114.254.44.156:50001

**Comment by ZeroClover** [comment]
你想要这个功能可以自己修改代码，几个%s的事

**Comment by piero66** [comment]
具体修改哪个文件啊？

**Comment by hdstar2009** [comment]
旧的服务器端版本有这个功能的。
今天安装了新的发现没这个功能了，也不知道要怎么改回来。

**Comment by breakwa11** [comment]
add
"connect_verbose_info": 1,
into your config file
if you want to see the connection info

**Comment by piero66** [comment]
@breakwa11 , added the line you mentioned in the configuration file, seems still cannot see the ss port which configured in client. yes, i can see the source China IP address and random port initialized from client. however, i want to check who is connecting to which website. that means i need to see the ss port user is using to connect. The source china IP address and random port is useless. really appriciate if any suggestions. thanks.

**Comment by hdstar2009** [comment]
@piero66 
you can use python server.py -v
see the debug information that will give u the client port

**Comment by hdstar2009** [comment]
@breakwa11 谢谢，搞定。不过想问下，这类功能更新变化要在什么地方能看到？

**Comment by ZeroClover** [comment]
@hdstar2009 https://github.com/breakwa11/shadowsocks/commits/manyuser

**Comment by piero66** [comment]
@hdstar2009 thanks!!!
