### ISSUE TITLE
问一下sql文件中的switch和type是干什么用的？

### ISSUE THREAD

**Issue by falseen** [breakwa11/shadowsocks#8]
看了一下，代码中似乎没有用到。

**Comment by falseen** [comment]
看了下之前的代码，原来是之前的版本留下的。

**Comment by falseen** [comment]
另外switchrule好像暂时还没起作用吧？以后准备实现什么功能呢？

**Comment by breakwa11** [comment]
switchrule用来让站长自己实现，用于设定哪些用户允许使用该节点，用于区分普通用户和高级用户，或实现没有签到多少天后自动禁用账号功能，其实现在已经有不少站的站长使用本配置实现这种功能了

**Comment by falseen** [comment]
@breakwa11 感谢解答。我看到源码中调用了switchrulu,但是这个函数不是永远返回True吗？

def isTurnOn(row):
    return True

还是说有其它我不知道的用法？(我才学python没多久)

**Comment by falseen** [comment]
我现在是通过数据库中的enable字段来控制停用或启用某个ss帐户的。虽然还有个switch字段，但源码中好像没用到。

**Comment by falseen** [comment]
我好像明白了，switchrule是让站长自己修改的么？

**Comment by breakwa11** [comment]
如果直接改enable，会导致所有的服务器都不能用，如果使用switchrule，那么可以控制用户能使用哪些服务器

**Comment by falseen** [comment]
@breakwa11 哦，明白了（之前还真没想过这个问题）。就是要站长手动修改switchrule文件是吧？但是我觉得这样还是很麻烦，没有直接在前端修改方便。
我想的是这样，站长通过前端修改数据库，把用户和其有权使用的服务器ip关联起来，然后ss这边只要判断当前用户是否有权使用当前服务器就行了。这样的话站长就不用对ss的文件做任何修改了，同时也保持了前端和后端的分离。
这个功能实现起来很简单，要修改的代码也很少。你觉得怎么样呢？如果可以的话我想我应该可以把它搞出来，但是在此之前我要对现在的代码有一个全面的了解，可能需要一段时间。（我很菜，但我很想帮忙完善这个项目）

**Comment by breakwa11** [comment]
有站长就类似这么干的，数据库加一个字符串字段，里面逗号分隔所有能用的服务器编号，然后后端判断当前服务器的编号是否出现在那个字段里就行了，但因为这个东西各站都不统一，所以就做成保留接口

**Comment by falseen** [comment]
@breakwa11 嗯，我觉得如果要统一的话也不是很难吧？统一之后这个后端就完美了，以后想要什么功能基本都可以通过前端实现。你觉得怎么样呢？

**Comment by ohyeah521** [comment]
@falseen 我也是新手，希望可以一起学习，把火炬传递下去，星星之火可以燎原。
