### ISSUE TITLE
manyuser版本不能在同一个VPS不同目录运行两次吗？

### ISSUE THREAD

**Issue by lowprofileusername** [breakwa11/shadowsocks#80]
想要连接2个不同的数据库，所以CP-R了一份运行了两次。两个数据库的端口没有冲突，但是好像同时运行两次后两个都连不上了。求解决办法。

**Comment by breakwa11** [comment]
可以，但不能有端口冲突，并且不能直接使用run脚本运行

**Comment by lowprofileusername** [comment]
请问怎么运行呢？现在端口不冲突
python /root/shadowsocks/server.py

我是这样运行的。好像第二次的可以用。最开始运行的那个就无效了？当然了运行两次./run.sh也不行。

**Comment by breakwa11** [comment]
监听的端口也不能冲突
直接用run会把前一个进程杀掉，直接用python命令运行是可以的
但直接用python命令运行的，只要按下ctrl+c就会强制当前的退出
你可以调整run脚本，并使用nohup运行，或screen等方式使其在后台运行

**Comment by liyangio** [comment]
@lowprofileusername 貌似还需要-C 指定config.json的配置文件
