### ISSUE TITLE
OSX无客户端可用

### ISSUE THREAD

**Issue by Xanthys** [breakwa11/shadowsocks#82]
我使用提供的https://github.com/shadowsocks/shadowsocks-iOS/wiki/Shadowsocks-for-OSX-Help 
安装后发现不支持SSR 
想过用python脚本运行，然而并没有。。。

**Comment by breakwa11** [comment]
MAC可以用GAX的插件，见ZeroNet，iPad/iPhone目前有rocket

**Comment by kid424** [comment]
OSX上python和libev客户端都可以用的，只不过要自己装一些缺少的组件

**Comment by chintj** [comment]
请问有详细的实例么。google了好多，尝试几次都失败了

**Comment by xekri** [comment]
我目前在用Surge的Mac版……
