### ISSUE TITLE
sspanel统计的流量是从ssr服务器版获取的吗？那么有没有统计udp的流量？

### ISSUE THREAD

**Issue by hdstar2009** [breakwa11/shadowsocks#87]
去sspanel问了下关于统计流量是否包括了tcp和udp流量，有人回答说sspanel是前端程序，流量实际是后台也就是ssr多用户版这样的服务端软件记录的，那么我想问的是，我用的shdowsocksR 数据库那个版本，流量是计算了udp还是仅仅tcp的流量？
ssr多用户版对流量的获取是通过iptables吗？

**Comment by breakwa11** [comment]
原版没有统计UDP流量，新版SSR修正了这问题，现在是统计了UDP流量的，统计和iptables无关

**Comment by hdstar2009** [comment]
好的，等我试下新版的ssr数据库版。sspanel那边也经常更新就怕和ssr配套没跟上，对接不上出问题啥的。

**Comment by Caixiaopig** [comment]
使用最新的ss-panel v3 ＋ ssr manyuser 最新版，提示节点不支持流量。是什么原因了？
![image](https://cloud.githubusercontent.com/assets/659662/15647795/8735a4a2-2698-11e6-9e9b-88a3ef9bf20f.png)

**Comment by breakwa11** [comment]
@Caixiaopig 那个说的是“部分节点”，说的是个提示信息，这个是新版本功能，你可以不用管

**Comment by Caixiaopig** [comment]
请问，流量数据统计在哪里了？数据库的几个表里边，只有user表有几个字段有统计。其他都没有。user表中的流量数据是ssr更新的吗？
谢谢。

**Comment by winer632** [comment]
貌似v3必须配套使用 https://github.com/orvice/shadowsocks-go/tree/mu
