### ISSUE TITLE
IPV6连接问题

### ISSUE THREAD

**Issue by suchengqing** [breakwa11/shadowsocks#88]
使用IPV6连接SS manyuser，客户端可以连接但是无法上传和下载
unable to resolve host"www.google.com":No address associate with hostname

**Comment by breakwa11** [comment]
dns_ipv6选项有打开吗

**Comment by suchengqing** [comment]
请问DNS_IPV6在哪里打开,

**Comment by breakwa11** [comment]
配置文件里

**Comment by suchengqing** [comment]
还是不行，防火墙是关闭的,系统是CENTOS 6 X64

**Comment by breakwa11** [comment]
你试试能不能直接用wget获取到，如果能，试试修改服务端的DNS
