### ISSUE TITLE
如何从服务端关闭UDP

### ISSUE THREAD

**Issue by liuchao0130** [breakwa11/shadowsocks#9]
请问下，我搭建了SS后，直接可以开UDP， 但是开UDP会更容易被检测到，如何自己手动关闭服务端的UDP呢。

**Comment by breakwa11** [comment]
目前只有改代码

**Comment by PlaneV** [comment]
用iptables应该可以
2015年8月31日 下午1:28，"breakwa11" <notifications@github.com>写道：

**Comment by asasuou** [comment]
iptables指定丢弃udp个别端口或是范围端口如何？

iptables- A INPUT -p udp -m multiport --dports xxx,xxxx,xxxx:xxxx -j REJECT

**Comment by asasuou** [comment]
错了，丢弃是DROP。

**Comment by PlaneV** [comment]
我有规则，可能更何用，今晚回去再发出来
2015年8月31日 下午6:18，"asasuou" <notifications@github.com>写道：

**Comment by PlaneV** [comment]
不好意思，记错了，我那个规则是tcp的，udp还是直接drop吧
iptables -A OUTPUT -p tcp -m multiport --dport
24,25,50,57,105,106,109,110,143,158,209,218,220,465,587 -j REJECT
--reject-with tcp-reset

在 2015年8月31日 下午6:27，Leo <planevv@gmail.com>写道：

**Comment by falseen** [comment]
改代码应该也不是很难吧？

**Comment by liuchao0130** [comment]
- - 有没有简单有效的办法呢  iptables 这个我不太喜欢用这个方式

**Comment by zhwalker** [comment]
ufw.这个简单有效
