### ISSUE TITLE
希望能够完善日志信息

### ISSUE THREAD

**Issue by nqzhang** [breakwa11/shadowsocks#97]
有人通过ss服务器滥发邮件却不知道是那个端口，是否可以打印出发邮件和BT下载特别平凡的端口

**Comment by ZeroClover** [comment]
破娃酱已经说了不会加这个功能。有需求自己修改源码。
SPAM封端口，BT用Nginx过滤流量

**Comment by nqzhang** [comment]
无语

**Comment by falseen** [comment]
如果加了这些功能的话可能会泄露用户的隐私，所以这也是没办法的事。现在的连接日志默认是隐藏的也是因为这个原因。
