### ISSUE TITLE
我想知道如何让服务端日志记录用户的链接端口，就是SS的链接端口，或者能分辨用户是谁的方法

### ISSUE THREAD

**Issue by ToyoDAdoubi** [breakwa11/shadowsocks#99]
有时候我要检查日志，看有没有什么违规情况，但是我不知道如何分辨用户，毕竟只是显示了，访问网站的地址/IP和端口，用户IP和用户的端口，而没有显示用户的SS链接端口或者其他可以分辨的信息。
所以想知道有没有什么方法可以改改。。

**Comment by ZeroClover** [comment]
破娃酱说了不会加入这个功能

**Comment by ToyoDAdoubi** [comment]
@ZeroClover 为什么那，我感觉很有用啊，否则用户违规都查不出来是谁违规的。。。

**Comment by ZeroClover** [comment]
所有审计类功能不会原生支持

**Comment by ToyoDAdoubi** [comment]
@ZeroClover 那你有没有什么办法呢，只需要知道端口就行了，老是有个用户违规，还查不出来。Python也看不懂
